### ISSUE TITLE
0.0.23: whey fails on building `sphinx-toolbox` 3.0.0

### ISSUE THREAD

**Issue by kloczek** [repo-helper/whey#66]
Looks like something is wrong with latest whey 0.0.23.
After upgarde to that version I'm not able now build `sphinx-toolbox` 3.0.0
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting dependencies for wheel...
* Building wheel...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 261, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/usr/lib/python3.8/site-packages/whey/__init__.py", line 63, in build_wheel
    with TemporaryPathPlus() as tmpdir, handle_tracebacks(show_traceback, WheyBackendTBHandler):
  File "/usr/lib/python3.8/site-packages/consolekit/tracebacks.py", line 182, in handle_tracebacks
    return cls()()
  File "/usr/lib/python3.8/site-packages/whey/utils.py", line 56, in __init__
    super().__init__(exception)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

ERROR Backend subprocess exited when trying to invoke build_wheel
```

**Comment by domdfcoding** [comment]
Which version of consolekit do you have installed? Whey now requires v1.4.1

**Comment by kloczek** [comment]
Just updated do 1.4.1 (that should be in install time dependencies)
Here is the redsult
```console
+ /usr/bin/sphinx-build -n -T -b man doc-source build/sphinx/man
Running Sphinx v5.0.1

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 443, in load_extension
    metadata = setup(app)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/./sphinx_toolbox/__init__.py", line 95, in setup
    app.setup_extension("sphinx_toolbox.more_autodoc.autoprotocol")
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 430, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/./sphinx_toolbox/more_autodoc/autoprotocol.py", line 153, in <module>
    from sphinx_toolbox.more_autodoc.generic_bases import _add_generic_bases
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/./sphinx_toolbox/more_autodoc/generic_bases.py", line 85, in <module>
    from sphinx_toolbox.more_autodoc.typehints import format_annotation
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/./sphinx_toolbox/more_autodoc/typehints.py", line 231, in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'

Exception occurred:
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/./sphinx_toolbox/more_autodoc/typehints.py", line 231, in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
The full traceback has been saved in /tmp/sphinx-err-ztacy55t.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
I'm using `sphinx` 5.0.1 and `sphinx-autodoc-typehints` 1.18.2.
